interio/interio/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('profiles.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

interio/profiles/urls.py
from django.urls import path
from .views import *
from . import views

app_name='profiles'

urlpatterns = [
    path('', Index.as_view(),name='home'),
    path('<int:pk>', PostDetail.as_view(), name='detail'),
    # path('contact', views.contact,name='contact'),
    path('add', views.PostCreate.as_view(),name='create'),
    path('update/<int:pk>', views.PostUpdate.as_view(),name='update'),
    path('delete/<int:pk>', views.PostDelete.as_view(),name='delete'),
    path('register', views.UserFormView.as_view(),name='register'),
    path('contact', views.Contact.as_view(),name='contact'),
    

]

interio/profiles/models.py
from django.db import models
from django.contrib.auth.models import User

class Post(models.Model):
    title = models.CharField(max_length=300)
    sub_title=models.CharField(max_length=250)
    description=models.CharField(max_length=500)
    image=models.ImageField(max_length=500)
    timestamp=models.DateTimeField(auto_now_add=True)
    created_by=models.ForeignKey(User, on_delete=models.CASCADE, null=True)  

    def __str__(self):
        return self.title

interio/profiles/forms.py
from django import forms
from .models import Post
from django.contrib.auth.models import User

class PostForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(attrs={'autofocus':'autofocus', 'class':'form-control', 'placeholder':'Title'}))
    sub_title = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Sub-title'}))
    image=forms.FileField()
    description = forms.CharField(widget=forms.Textarea(attrs={'class':'form-control', 'placeholder':'Description'}))

    class Meta:
        model = Post
        fields= ('title', 'sub_title', 'image', 'description')

class UserForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'autofocus':'autofocus', 'class':'form-control', 'placeholder':'Username'}))
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'First Name'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Last Name'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control', 'placeholder':'Email'}))
    password = forms.CharField(widget = forms.PasswordInput(attrs={'class':'form-control', 'placeholder':'Password'}))
    
    class Meta:
        model = User
        fields=['username', 'first_name', 'last_name', 'email', 'password']

class LoginForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'autofocus':'autofocus', 'class':'form-control', 'placeholder':'Username'}))
    password = forms.CharField(widget = forms.PasswordInput(attrs={'class':'form-control', 'placeholder':'Password'}))
    
    class Meta:
        model = User
        fields=['username', 'password']


class ContactForm(forms.Form):
    name = forms.CharField(widget=forms.TextInput(attrs={'autofocus':'autofocus', 'class':'form-control', 'placeholder':'Name'}))    
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control', 'placeholder':'Email'}))
    title = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Title'}))    
    message = forms.CharField(widget=forms.Textarea(attrs={'class':'form-control', 'placeholder':'Message'}))
    

interio/profiles/views.py
from django.shortcuts import render
from django.views import generic
from .models import Post
from django.contrib.auth import views
from .forms import *
from django.urls import reverse_lazy
from django.shortcuts import redirect
from django.contrib.auth import authenticate, login
from django.core.mail import send_mail


class Index(generic.ListView):
    model = Post
    template_name = 'index.html'
    context_object_name = 'posts'

    def get_queryset(self):
        return Post.objects.all()


class PostDetail(generic.DetailView):
    model = Post
    template_name = 'detail.html'
    context_object_name = 'post'


class Login(views.LoginView):
    template_name = 'registration/login.html'


class PostCreate(generic.CreateView):
    model = Post
    form_class = PostForm
    template_name = 'postform.html'
    # success_url = reverse_lazy('profiles:home')

    def form_valid(self, form, *args, **kwargs):
        obj = form.save(commit=False)
        obj.created_by = self.request.user
        obj.save()
        return super(PostCreate, self).form_valid(form, *args, **kwargs)

    def get_success_url(self):
        return reverse_lazy('profiles:detail', kwargs={'pk' : self.object.pk})

class PostUpdate(generic.UpdateView):
    model = Post
    form_class = PostForm
    template_name = 'postform.html'
    success_url = reverse_lazy('profiles:detail')

    def get_success_url(self, *args, **kwargs):
        return reverse_lazy('profiles:detail', kwargs={'pk':self.kwargs['pk']})

class PostDelete(generic.DeleteView):
    model = Post
    # template_name = 'postform.html'
    success_url = reverse_lazy('profiles:home')

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)


def contact(request):
    return render(request,'contact.html')


class UserFormView(generic.View):
	form_class = UserForm
	template_name = 'registration/signup.html'	

	#display blank form
	def get(self, request):
		form = self.form_class(None)
		return render(request, self.template_name, {'form':form})

	# process form data
	def post(self, request):
		form = self.form_class(request.POST)

		if form.is_valid():
			user = form.save(commit = False)

			#cleaned (normalised) data

			username_var = form.cleaned_data['username']
			password_var = form.cleaned_data['password']
			email_var = form.cleaned_data['email']
			user.set_password(password_var)
			
			try:
				email_exists = User.objects.get(email = email_var)
				form.add_error('email', 'E-Mail Already Exists')
				return render(request, self.template_name, {'form':form})
			
			except:
				user.save()


				#returns User objects if credentials are correct
				user = authenticate(username = username_var, password = password_var)

				if user is not None:
					if user.is_active:
						login(request, user)
						return redirect('profiles:home')

		return render(request, self.template_name, {'form':form})

class Contact(generic.FormView):
    form_class = ContactForm
    template_name = 'contact.html'

    def get_success_url(self, *args, **kwargs):
        return reverse_lazy('profiles:home')

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            send_mail(form.cleaned_data['title'] + " - Query by " + form.cleaned_data['name'] + " - " + form.cleaned_data['email'],
                form.cleaned_data['message'] ,'abhinavmahajan004@gmail.com',
            ['abhinavmahajan1998@gmail.com'], fail_silently=True )
            return self.form_valid(form)
        else:
            return self.form_invalid(form)




    

interio/templates/contact.html
{% extends 'index.html' %}

{% block body %}
<section class="ftco-section ftco-no-pt ftco-no-pb contact-section" style="padding-top: 4%;">


	<div class="container">
		<div class="row block-9">

			<div class="col-md-6 order-first ftco-animate">
				<h3 style="position:relative; top:50px;">Contact</h3>
				<form action="" class="p-4 p-md-5" method="POST" enctype="multipart/form-data">
					{% csrf_token %}
					{% for field in form %}
					<div class="form-group">
						<span class="text-danger small">{{ field.errors }}</span>
						{{ field }}
					</div>
					{% endfor %}
					<div class="form-group">
						<input type="submit" value="Submit" class="btn btn-primary py-3 px-5">
					</div>
				</form>
			</div>
		</div>




	</div>
</section>
{% endblock %}

interio/templates/detail.html
{% extends 'index.html' %}

{% block body %}


<section class="ftco-section ftco-no-pt" style="padding-top:7%;">
  <div class="container">
    <div class="row d-flex justify-content-center">
      <div class="col-md-10 text-center d-flex ftco-animate">
        <div class="blog-entry justify-content-end">
          <a href="#" class="block-20 img" style="background-image: url({{ post.image.url }});">
          </a>
          <div class="text pt-4 px-md-5">
            <div class="meta mb-3">
              <div><a href="#">{{ post.timestamp }}</a></div>
              <div><a href="#">{{ post.created_by.username }}</a></div>
              <!-- <div><a href="#" class="meta-chat"><span class="icon-chat"></span> 3</a></div> -->
            </div>
            <h3 class="heading mt-2"><a href="#">{{ post.title }}</a></h3>
            <p>{{ post.description }}</p>
            <!-- <p><a href="blog-single.html" class="btn-custom">Continue <span class="icon-long-arrow-right"></span></a></p> -->
          </div>
          <div class="form-group">
            {% if post.created_by.username == request.user.username %}
            <a href="{% url 'profiles:update' post.pk %}"><button value="Edit" class="btn btn-warning py-3 px-5">Edit
                Post</button></a>
            <a href="{% url 'profiles:delete' post.pk %}"><button value="Edit" class="btn btn-danger py-3 px-5">Delete
                Post</button></a>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>



</section>
{% endblock %}

interio/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
  <title>Personal Perch</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Abril+Fatface&display=swap" rel="stylesheet">

  {% load static %}

  <link rel="stylesheet" href="{% static 'css/open-iconic-bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/animate.css' %}">

  <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">

  <link rel="stylesheet" href="{% static 'css/aos.css' %}">

  <link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}">

  <link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.css' %}">
  <link rel="stylesheet" href="{% static 'css/jquery.timepicker.css' %}">


  <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
  <link rel="stylesheet" href="{% static 'css/icomoon.css' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>

  <div class="page">
    <nav id="colorlib-main-nav" role="navigation">
      <a href="#" class="js-colorlib-nav-toggle colorlib-nav-toggle active"><i></i></a>
      <div class="js-fullheight colorlib-table">
        <div class="img" style="background-image: url(images/bg_3.jpg);"></div>
        <div class="colorlib-table-cell js-fullheight">
          <div class="row no-gutters">
            <div class="col-md-12 text-center">
              <h1 class="mb-4"><a href="{%url 'profiles:home' %}" class="logo">Personal<span>Perch</span></a></h1>
              <ul>
                <li class="active"><a href="{%url 'profiles:home' %}"><span>Home</span></a></li>
                <li><a href="{%url 'profiles:contact'%}"><span>Contact</span></a></li>
                {% if request.user.is_authenticated %}
                <li><a href="{% url 'profiles:create' %}"><span>Add Post</span></a></li>
                <li><a href="{% url 'logout' %}"><span>Logout</span></a></li>
                {% else %}
                <li><a href="{% url 'login' %}"><span>Login</span></a></li>
                {% endif %}
              </ul>
            </div>
          </div>
        </div>
      </div>
    </nav>

    <div id="colorlib-page">
      <header>
        <div class="container">
          <div class="colorlib-navbar-brand">
            <a class="colorlib-logo" href="{% url 'profiles:home' %}">Personal<span>Perch</span></a>
          </div>
          <a href="#" class="js-colorlib-nav-toggle colorlib-nav-toggle"><i></i></a>
        </div>
      </header>


      <section class="hero">
        <div class="con d-flex align-items-center justify-content-end" style="visibility: hidden;">
          <!--- a href="#">View All Project</a>% }-->
        </div>

        {% block body %}

        <div class="home-slider owl-carousel js-fullheight">

          {% for post in posts %}
          <div class="slider-item =js-fullheight">
            <!-- <div class="overlay"></div> -->
            <div class="container">
              <div class="row d-md-flex no-gutters slider-text js-fullheight align-items-center justify-content-end"
                data-scrollax-parent="true">
                <div class="one-third order-md-last img" style="background-image:url({{ post.image.url }});">
                  <!-- <div class="overlay"></div> -->
                </div>
                <div class="one-forth d-flex  align-items-center ftco-animate"
                  data-scrollax=" properties: { translateY: '70%' }">
                  <!-- <a href="https://vimeo.com/45830194" class="icon-video popup-vimeo d-flex justify-content-center align-items-center">
		    						<span class="ion-ios-play play"></span>
		    					</a> -->
                  <div class="text">
                    <h2><a href="{% url 'profiles:detail' post.pk %}">{{ post.title }}</a></h2>
                    <span class="cat">{{ post.sub_title }}</span>
                    <div class="my-5">
                      <p>{{ post.description }}</p>
                    </div>
                    <a href="{% url 'profiles:detail' post.pk %}">View Project</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
          {% endfor %}






        </div>
      </section>


      <div class="col-md-12 ftco-animate text-center" style="padding-top:5%">

        <h1 class="bread">All Posts</h1>
      </div>

      <section class="ftco-section ftco-no-pt">
        <div class="container">
          <div class="row">
            {% for post in posts %}
            <div class="col-md-4 ftco-animate">
              <div class="project">
                <a href="{% url 'profiles:detail' post.pk %}"
                  class="img d-flex align-items-center justify-content-center"
                  style="background-image:url({{ post.image.url }});">
                  <div class="icon d-flex align-items-center justify-content-center">
                    <span class="ion-ios-search"></span>
                  </div>
                </a>
                <div class="text">
                  <span class="subheading">{{ post.sub_title }}</span>
                  <h3 class="mb-0"><a href="{% url 'profiles:detail' post.pk %}">{{ post.title }}</a></h3>
                </div>
              </div>
            </div>
            {% endfor %}
          </div>
      </section>

      {% endblock %}




      <!-- loader -->
      <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px">
          <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee" />
          <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"
            stroke="#F96D00" /></svg></div>

    </div>
  </div>


  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/jquery-migrate-3.0.1.min.js' %}"></script>
  <script src="{% static 'js/popper.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
  <script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
  <script src="{% static 'js/jquery.stellar.min.js' %}"></script>
  <script src="{% static 'js/owl.carousel.min.js' %}"></script>
  <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
  <script src="{% static 'js/aos.js' %}"></script>
  <script src="{% static 'js/jquery.animateNumber.min.js' %}"></script>
  <script src="{% static 'js/scrollax.min.js' %}"></script>
  <script
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
  <script src="{% static 'js/google-map.js' %}"></script>
  <script src="{% static 'js/main.js' %}"></script>
</body>

</html>

interio/templates/postform.html
{% extends 'index.html' %}

{% block body %}
<section class="ftco-section ftco-no-pt ftco-no-pb contact-section" style="padding-top: 4%;">


    <div class="container">
        <div class="row block-9">

            <div class="col-md-6 order-first ftco-animate">
                <form action="" class="p-4 p-md-5" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% for field in form %}
                    <div class="form-group">
                        <span class="text-danger small">{{ field.errors }}</span>
                        {{ field }}
                    </div>
                    {% endfor %}
                    <div class="form-group">
                        <input type="submit" value="Submit" class="btn btn-primary py-3 px-5">
                    </div>
                </form>
            </div>
        </div>




    </div>
</section>
{% endblock %}